spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: ${JWT_SECRET}