spring:

  application:
    name: reporting-service
  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:mysql://localhost:3306/inventra_reporting_db
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8082